<!DOCTYPE html>
<html>
<head>
    <title>WMarket</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
<header>
    <h1>Welcome to WMarket</h1>
</header>
<nav>
    <ul>
        <li><a href="#">Home</a></li>
        <li><a href="#">Products</a></li>
        <li><a href="#">Contact Us</a></li>
    </ul>
</nav>
<h2>Product description</h2>
<h3>${product.title}</h3>
<h4>${product.description}</h4>
<p>${product.brand}</p>
<b>${product.price}</b>
</body>
</html>
